In [1]:
import numpy as np

In [2]:
ar = np.arange(20).reshape(4, 5)
ar

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [3]:
ar[2:]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [4]:
ar[2:, :2]

array([[10, 11],
       [15, 16]])

In [7]:
ar[2:][:-2]

array([], shape=(0, 5), dtype=int32)

In [9]:
ar[::-1,, ::-1]

SyntaxError: invalid syntax (1463581034.py, line 1)