In [1]:
import numpy as np

In [3]:
ar = np.arange(12).reshape(2, 2, 3)
ar

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [4]:
ar[0]

array([[0, 1, 2],
       [3, 4, 5]])

In [5]:
ar[0][1]

array([3, 4, 5])

In [6]:
ar[0, 1, 2]

5