In [1]:
import numpy as np

In [2]:
a = np.random.randint(-10, 10, 5)
b = np.random.randint(-10, 10, 5)

In [3]:
a

array([ 6,  5,  2, -4,  6])

In [4]:
b

array([  1, -10,  -6,   2, -10])

In [5]:
a * b

array([  6, -50, -12,  -8, -60])

In [6]:
a + b * 2

array([  8, -15, -10,   0, -14])

In [7]:
a ** 2

array([36, 25,  4, 16, 36])

In [8]:
a > 5

array([ True, False, False, False,  True])

In [9]:
a % 2 == 1

array([False,  True, False, False, False])