In [1]:
import numpy as np

In [5]:
np.random.random((2, 4))

array([[0.9008558 , 0.60596573, 0.6409116 , 0.23306989],
       [0.89326558, 0.57403482, 0.64136058, 0.48124034]])

In [6]:
np.random.uniform(3.5, 4, (3, 3))

array([[3.61366449, 3.95998182, 3.93989108],
       [3.94684162, 3.72044429, 3.50991613],
       [3.63335339, 3.6308241 , 3.55143777]])

In [8]:
np.random.randint(0, 7, (2, 3, 4))

array([[[0, 1, 6, 4],
        [5, 1, 1, 5],
        [0, 3, 1, 3]],

       [[6, 5, 2, 3],
        [5, 6, 2, 3],
        [1, 3, 5, 3]]])

In [9]:
np.random.randint(-5, 5, 7)

array([-3,  0, -4,  2,  4,  3,  3])