In [1]:
import numpy as np

In [2]:
ar = np.random.randint(0, 10, 5)
ar

array([9, 6, 0, 6, 6])

In [3]:
np.exp(ar)

array([8.10308393e+03, 4.03428793e+02, 1.00000000e+00, 4.03428793e+02,
       4.03428793e+02])

In [5]:
np.log(ar[ar > 0])

array([2.19722458, 1.79175947, 1.79175947, 1.79175947])

In [7]:
np.log10([ar > 0])

C:\Users\KMS\AppData\Local\Temp\ipykernel_11760\1407038388.py:1: RuntimeWarning: divide by zero encountered in log10
  np.log10([ar > 0])


array([[  0.,   0., -inf,   0.,   0.]], dtype=float16)

In [8]:
np.sin(ar)

array([ 0.41211849, -0.2794155 ,  0.        , -0.2794155 , -0.2794155 ])

In [9]:
np.cos(ar)

array([-0.91113026,  0.96017029,  1.        ,  0.96017029,  0.96017029])

In [10]:
np.abs(ar)

array([9, 6, 0, 6, 6])